version: "3.8"
services:
  # db:
  #   image: mysql:5.7
  #   container_name: mysql-server
  #   healthcheck:
  #     test: "mysql --user=root --password=root --execute \"SHOW DATABASES;\""
  #     # timeout: 10s
  #     # retries: 10
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: webinterface
  #     MYSQL_HOST: localhost
  #     MYSQL_USER: root
  #     MYSQL_USER_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d/:ro

  dns:
    build: ./dnsmasq/
    hostname: localhost
    container_name: dnsmasq-exec
    ports:
      - "8081:8081"
      - "69:69"
      - "53:53"
    volumes:
      # - ./db:/docker-entrypoint-initdb.d/:ro
      - ./dns:/etc/dnsmasq.d/:rw
      - ./dns:/etc/dnsmasq/:rw
      - ./dns:/usr/local/bin:rw
      # - app-data:/
    cap_add:
      - NET_ADMIN
    # links:
    #   - app:app
    #   - db:db

  webapp:
    build: ./webapp
    container_name: webapp
    # depends_on:
    #   db:
    #     condition: service_healthy
    ports:
      - "5000:5000"
  
  drawio:
    build: ./designer/alpine/
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8082:8080
      - 8443:8443
    environment:
      PUBLIC_DNS: systronaut
      ORGANISATION_UNIT: admin
      ORGANISATION: com
      CITY: Düsseldorf
      STATE: NW
      COUNTRY_CODE: DE
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
  
  # config-generator:
  #   build: ./config-generator
  #   container_name: config-generator
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d/:ro
  #     - ./dns:/etc/dnsmasq.d/:rw
  #     - ./dns:/etc/dnsmasq/:rw