---

- hosts: pxeserver
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      apt: 
        name: python-pip 
        state: present
      
    - name: install docker-py
      pip: 
        name: docker-py
      
    - name: Build Docker image from Dockerfile
      docker_image:
        name: dnsmasq
        path: docker
        state: build
        
    - name: Running the container
      docker_container:
        image: dnsmasq:latest
        path: docker
        state: running